### PR TITLE
Adding help describing space scoped private brokers

### PR DESCRIPTION
**Pull request by dieucao**
Hi!
I'd appreciate getting some feedback on the content/layout/language of the changes that I've made to add content describing space scoped private brokers.
Let me know if you have any questions about these changes.
Thanks,
Dieu

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks Dieu!

**Comment by pspinrad** [comment]
Hi again-- a few q's, hopefully easy-- thanks for any answers or pointers:

1. What's a "Space Scoped Private Broker" / what does the "--space-scoped" flag do?  Phrase not used elsewhere in docs, would be great to define here.

2. ^^^ is same as "Space Scoped Private Service Brokers" right?

3. You say:
> two steps are required to make its services available to end users in all organizations or a limited number of organizations by service plan.

Thanks!

**Comment by dieucao** [comment]
1. Adding the --space-scoped flag creates a service broker that is tied/scoped to the space where the plans will automatically be visible to users of the space.  Also, by specifying --space-scoped will make it create the service broker against the currently targeted space.  Additionally, Space Developers will now have the capability to create these types of service brokers that are specific to a space.  Without that flag, only admins are able to create service brokers whose plans visibility can then be managed at a deployment level or org level.

2. Yes, it's the same. Perhaps the more lengthy name would be more correct.

3. I'm unclear what the third question is?

**Comment by pspinrad** [comment]
Third question-- sorry, actual question disappeared somehow: is "service plan" at end of sentence the thing that defines "services available" earlier?

So, the --space-scoped flag to a service broker restricts their services to a single space, right? This means that the services are invisible to users who are not members of the space (and are not admins), and visible to users who are members of the space-- correct?

And if a developer within a space wants to create a service broker scoped to their space, they can use the --space-scoped flag, right?  But they can't create service brokers that are accessible at the org or deployment level-- that can only be done by admins?

So, what if a space developer leaves the --space-scoped flag off of their "cf create-service-broker" call?  Will it not create the broker, or will it automatically scope it to their space anyway?

**Comment by dieucao** [comment]
3. Yes, service plan is the thing that needs to be visible in order to create service instances that the service broker is offering.

Yes, the space scoped flag limits the service plans and service instances to the same space that the service broker is created against.

Yes, if a space developer wants to create a service broker scoped to the space they can use that flag, and only admins can create service brokers that can make service plans visible at the deployment wide or org(s) level.

If a space developer leaves off the space scoped flag they'll get a permission denied error.

**Comment by pspinrad** [comment]
Two more q's:

1. You say:
> This page assumes you are using cf CLI v6.16

OK to say something like "cf CLI v6.16 or later" ?

2. Since current version of cf CLI is v6.15 per https://github.com/cloudfoundry/cli/releases -- is this PR ready to go now, or should we wait?

Thanks again--

**Comment by dieucao** [comment]
I think "cf CLI v6.16 or later" is fine although we have language in other sections that use the word minimum instead so that could perhaps be cleaned up/made consistent one way or the other?

I expect the cli team will be bumping to v6.16 this week or early next week.  I can send an update once it's up.

**Comment by pspinrad** [comment]
@dieucao great, yes please send update when change is ready for prime time.

**Comment by dieucao** [comment]
@pspinrad Change is ready for prime time now.

**Comment by pspinrad** [comment]
Thanks Dieu!

**Pull request merged**
