### PR TITLE
Update Last Operation documentation to include parameters

### PR DESCRIPTION
**Pull request by sax**
Please don't accept this until Nick accepts [this story](https://www.pivotaltracker.com/story/show/114769745).

Signed-off-by: Rizwan Reza <rreza@pivotal.io>

### CODE REVIEW

**Comment by SocalNick** [comment]
Hi Docs,

I think this is ready to go, but it applies to CF-238 which won't be out until at least next week. How do we normally get docs published when CF-Release is cut?

**Comment by bentarnoff** [comment]
Thanks, @SocalNick. We can keep this blocked until CF-238 is cut, and then we can merge this PR and push our staging site to prod so it shows live. If you could ping us when CF-238 is cut, that'd be great!

**Comment by SocalNick** [comment]
Heads up to anyone that intends to make additional commits to this branch. I rebased against master to eliminate the merge conflict. Sorry for the inconvenience.

**Comment by SocalNick** [comment]
@bentarnoff another one for CF-238 that is out now

**Comment by bentarnoff** [comment]
Thanks, @SocalNick and @sax !

**Pull request merged**
