### PR TITLE
API Version v2.11

### PR DESCRIPTION
**Pull request by ablease**
This adds a new `bindable` field to the service plan objects in the catalog. See [this story](https://www.pivotaltracker.com/story/show/134136079) and (this PR)[https://github.com/cloudfoundry/cloud_controller_ng/pull/725] for more info.

**Please do NOT merge until @avade and @SocalNick give their okay.**

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @ablease. We will block this until @avade and @SocalNick give the thumbs up.

**Comment by avade** [comment]
@abbyachau have you finished your changes to the docs?

**Comment by avade** [comment]
@shalako / @abbyachau / @pspinrad - has the work on the docs to extract services things been completed? We can then re-do the PR.

The feature has been merged but not in a CF release version.

cc @SocalNick

**Comment by shalako** [comment]
@avade and I discussed that 2.11 should not be blocked on the changes @abbyachau and I are working on, because our work is on the `generic-service-broker-api-#134456375` branch and we can rebase the 2.11 changes.

**Comment by SocalNick** [comment]
CAPI has cut v1.12.0, this can be merged

**Comment by SocalNick** [comment]
@ablease @avade would you be able to take a look at the conflicts?

**Comment by Samze** [comment]
@SocalNick we have resolved the merge conflicts and updated the CF release & CC API version numbers.

Cheers,

Sam & @st3v

**Comment by avade** [comment]
@bentarnoff OK to merge now as this change is in https://github.com/cloudfoundry/cf-release/releases/tag/v250

**Comment by animatedmax** [comment]
Thank you, avade

**Pull request merged**
