### PR TITLE
id text clarification

### PR DESCRIPTION
**Pull request by krujos**
While writing a service broker I found myself thinking about what `id` meant in relation to the URI on the preceding lines. This makes it clearer for me, does it for others?

### CODE REVIEW

**Comment by krujos** [comment]
In regards to the CLA, I'm a pivotal employee, anything additional I need to do there?

**Comment by jbayer** [comment]
@krujos we just need to get you listed appropriately.

josh is part of pivotal, so please proceed.

**Comment by krujos** [comment]
Thanks!

**Comment by elenasharma** [comment]
Thanks, @krujos!

**Pull request merged**
